# Generated by Django 4.2.1 on 2023-05-29 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_fashion_electronics_appliance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronics',
            name='product',
        ),
        migrations.RemoveField(
            model_name='fashion',
            name='product',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='product',
        ),
        migrations.DeleteModel(
            name='Appliance',
        ),
        migrations.DeleteModel(
            name='Electronics',
        ),
        migrations.DeleteModel(
            name='Fashion',
        ),
        migrations.DeleteModel(
            name='Mobile',
        ),
    ]
