# Generated by Django 4.2.1 on 2023-06-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_electronics_product_remove_fashion_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='zipcode',
            field=models.BigIntegerField(),
        ),
    ]
